const BR_GAMES=[
 {id:'bra-mar',group:'Grupo C',phase:'Fase de grupos',date:'2026-06-13T18:00:00-03:00',home:'Brasil',away:'Marrocos',homeCode:'BRA',awayCode:'MAR',homeFlag:'🇧🇷',awayFlag:'🇲🇦',stadium:'Lincoln Financial Field, Filadélfia',status:'scheduled'},
 {id:'bra-hai',group:'Grupo C',phase:'Fase de grupos',date:'2026-06-19T21:30:00-03:00',home:'Brasil',away:'Haiti',homeCode:'BRA',awayCode:'HAI',homeFlag:'🇧🇷',awayFlag:'🇭🇹',stadium:'MetLife Stadium, Nova Jersey',status:'scheduled'},
 {id:'sco-bra',group:'Grupo C',phase:'Fase de grupos',date:'2026-06-24T19:00:00-03:00',home:'Escócia',away:'Brasil',homeCode:'SCO',awayCode:'BRA',homeFlag:'🏴',awayFlag:'🇧🇷',stadium:'Hard Rock Stadium, Miami',status:'scheduled'}
];
const ADMIN_PIN='2026';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const store={get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
let state={page:'home',user:store.get('user',null),games:store.get('games',BR_GAMES),bets:store.get('bets',[]),admin:store.get('admin',false),theme:store.get('theme','dark')};
function init(){if(!store.get('games')) store.set('games',BR_GAMES); $('#themeBtn').onclick=toggleTheme; applyTheme(); render(); setInterval(()=>{renderIf(['home','games']);},60000); if('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js').catch(()=>{});}
function showToast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2400)}
function go(p){state.page=p;render();window.scrollTo({top:0,behavior:'smooth'})}
function renderIf(pages){if(pages.includes(state.page)) render()}
function toggleDrawer(force){const open=force??!$('#drawer').classList.contains('open');$('#drawer').classList.toggle('open',open);$('#shade').classList.toggle('show',open)}
function logout(){state.user=null;state.admin=false;store.set('user',null);store.set('admin',false);toggleDrawer(false);go('home');showToast('Conta desconectada')}
function toggleTheme(){state.theme=state.theme==='dark'?'light':'dark';store.set('theme',state.theme);applyTheme()} 
function applyTheme(){document.body.classList.toggle('light',state.theme==='light');$('#themeBtn').textContent=state.theme==='dark'?'☀️':'🌙'}
function updateShell(){const name=state.user?.name||'Visitante'; const initial=(name[0]||'K').toUpperCase();$('#avatarBtn').textContent=initial;$('#drawerAvatar').textContent=initial;$('#drawerName').textContent=name;$('#drawerPts').textContent=getRanking().find(r=>r.phone===state.user?.phone)?.pts||0;$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===state.page));}
function render(){updateShell(); if(!state.user && state.page!=='tutorial') return renderLogin(); const map={home, games, ranking, stats, admin, tutorial}; $('#main').innerHTML=(map[state.page]||home)(); bindPage();}
function renderLogin(){ $('#main').innerHTML=`<section class="login"><div class="hero"><div class="logo-big">🇧🇷</div><h1>Bolão Seleção 2026</h1><p>Entre com seu WhatsApp para palpitar nos jogos do Brasil.</p></div><div class="card"><div class="field"><label>Seu nome</label><input id="loginName" placeholder="Ex: Kelly Menezes"></div><div class="field"><label>WhatsApp</label><input id="loginPhone" inputmode="numeric" placeholder="11999999999"></div><button class="save" id="loginBtn">Entrar no bolão</button><button class="save secondary" onclick="go('tutorial')">📖 Ver tutorial</button></div></section>`; $('#loginBtn').onclick=()=>{const name=$('#loginName').value.trim(); const phone=$('#loginPhone').value.replace(/\D/g,''); if(name.length<2||phone.length<10)return showToast('Preencha nome e WhatsApp'); state.user={name,phone};store.set('user',state.user);go('home');showToast('Login feito com sucesso')};}
function home(){return `<section class="hero"><div class="logo-big">🐆🇧🇷</div><h1>Bolão Seleção 2026</h1><p>Apenas jogos da Seleção Brasileira · Login por WhatsApp · Ranking automático</p><div class="hero-stats"><div><b>${state.games.length}</b><span>Jogos</span></div><div><b>${state.bets.length}</b><span>Palpites</span></div><div><b>${getRanking()[0]?.pts||0}</b><span>Líder</span></div></div></section><div class="section-title"><h2>Próximos Jogos</h2><button class="link" onclick="go('games')">Ver todos</button></div>${state.games.map(gameCard).join('')}<div class="section-title"><h2>Top Apostadores</h2><button class="link" onclick="go('ranking')">Ver todos</button></div><div class="card">${rankRows(getRanking().slice(0,5))}</div>`}
function games(){return `<div class="section-title"><h2>⚽ Jogos do Brasil</h2><span class="pill">${state.games.length} jogos</span></div><div class="card"><div class="grid2"><select id="phaseFilter"><option value="">Todas as fases</option><option>Fase de grupos</option><option>Oitavas</option><option>Quartas</option><option>Semifinal</option><option>Final</option></select><select id="statusFilter"><option value="">Todos status</option><option value="scheduled">Agendado</option><option value="live">Ao vivo</option><option value="finished">Encerrado</option></select></div></div><div id="gamesList">${state.games.map(gameCard).join('')}</div>`}
function gameCard(g){const bet=getBet(g.id); const done=g.status==='finished'; return `<article class="card game-card" data-game="${g.id}"><div class="game-head"><span class="pill">${g.group}</span><div><span class="time">${fmt(g.date)}</span> <span class="countdown">${statusText(g)}</span></div></div><div class="teams"><div class="team"><div class="flag">${g.homeFlag}</div><b>${g.home}</b><span>${g.homeCode}</span></div><div class="vs">${done?`<span class="score">${g.homeScore??0}-${g.awayScore??0}</span>`:'VS'}</div><div class="team"><div class="flag">${g.awayFlag}</div><b>${g.away}</b><span>${g.awayCode}</span></div></div><div class="divider"></div>${done?`<div class="bet-title">${bet?'Seu palpite: '+bet.home+' x '+bet.away:'Sem palpite neste jogo'}</div>`:betBox(g,bet)}<div class="stadium">📍 ${g.stadium}</div></article>`}
function betBox(g,bet={home:0,away:0}){return `<div class="bet-title">🎯 FAZER PALPITE</div><div class="bet-grid"><div class="team-name">${g.home}</div><div class="counter"><button data-act="minus" data-side="home" data-game="${g.id}">−</button><div class="num" id="h-${g.id}">${bet?.home??0}</div><button data-act="plus" data-side="home" data-game="${g.id}">+</button></div><div class="drawbox">✕<br><small>empate</small></div><div class="counter"><button data-act="minus" data-side="away" data-game="${g.id}">−</button><div class="num" id="a-${g.id}">${bet?.away??0}</div><button data-act="plus" data-side="away" data-game="${g.id}">+</button></div><div class="team-name">${g.away}</div></div><button class="save" data-save="${g.id}">${bet?'Editar palpite':'Salvar palpite'}</button>`}
function ranking(){const r=getRanking();return `<div class="section-title"><h2>📊 Ranking do Bolão</h2></div><div class="card"><p class="pill">Sistema: 3 pontos placar exato · 1 ponto vencedor/empate · 0 errou</p></div><div class="rank-podium"><div class="pod"><span class="medal">🥈</span><b>${r[1]?.name||'-'}</b><small>${r[1]?.pts||0} pts</small></div><div class="pod first"><span class="medal">🥇</span><b>${r[0]?.name||'-'}</b><small>${r[0]?.pts||0} pts</small></div><div class="pod"><span class="medal">🥉</span><b>${r[2]?.name||'-'}</b><small>${r[2]?.pts||0} pts</small></div></div><div class="card">${rankRows(r)}</div>`}
function stats(){const my=state.bets.filter(b=>b.phone===state.user?.phone); const pts=getRanking().find(r=>r.phone===state.user?.phone)?.pts||0; const exact=my.filter(b=>scoreBet(b)===3).length, win=my.filter(b=>scoreBet(b)===1).length, wrong=my.filter(b=>scoreBet(b)===0).length; return `<div class="section-title"><h2>📈 Minhas Estatísticas</h2></div><div class="stat-grid"><div class="card stat">🏆<b>${pts}</b><span>Pontos totais</span></div><div class="card stat">📊<b>${pos()}</b><span>Posição</span></div><div class="card stat">🎯<b>${my.length?Math.round((exact+win)/my.length*100):0}%</b><span>Aproveitamento</span></div><div class="card stat">📝<b>${my.length}</b><span>Palpites</span></div></div><div class="card"><h2>Distribuição dos palpites</h2><p>Placar exato (+3): <b>${exact}</b></p><p>Acertou vencedor (+1): <b>${win}</b></p><p>Errou (0): <b>${wrong}</b></p><p>Aguardando: <b>${my.filter(b=>scoreBet(b)===null).length}</b></p></div>`}
function admin(){if(!state.admin)return `<section class="admin-lock"><div class="hero"><h1>🔐 Painel Admin</h1><p>Acesso apenas da Kelly.</p></div><div class="card"><div class="field"><label>PIN Admin</label><input id="pin" inputmode="numeric" placeholder="Digite o PIN"></div><button class="save" id="pinBtn">Entrar no admin</button></div></section>`; return `<div class="section-title"><h2>🔐 Painel Admin</h2><span class="pill">Kelly</span></div><div class="card admin-actions"><button class="save secondary" id="seedBtn">Restaurar jogos do Brasil</button><button class="save secondary" id="exportBtn">Exportar palpites</button><button class="save danger" id="clearRankBtn">Limpar ranking/palpites</button><button class="save secondary" id="autoBtn">Simular atualização automática</button></div><div class="card"><h2>Lançar resultado</h2><div class="field"><label>Jogo</label><select id="resGame">${state.games.map(g=>`<option value="${g.id}">${g.home} x ${g.away}</option>`)}</select></div><div class="grid2"><div class="field"><label>Gols casa</label><input id="resH" type="number" min="0" value="0"></div><div class="field"><label>Gols fora</label><input id="resA" type="number" min="0" value="0"></div></div><button class="save" id="saveResult">Salvar resultado e recalcular</button></div><div class="card"><h2>Palpites de todos</h2><div id="allBets">${allBetsTable()}</div></div><div class="card"><h2>Importar jogos por JSON</h2><textarea id="jsonGames" rows="8" placeholder='Cole JSON de jogos aqui'></textarea><button class="save secondary" id="importGames">Enviar jogos</button></div>`}
function tutorial(){return `<div class="section-title"><h2>📖 Como funciona o Bolão</h2></div>${['Crie sua conta com nome e WhatsApp.','Entre em Jogos e faça seu palpite.','Enquanto o jogo não começar, você pode editar.','Placar exato vale 3 pontos. Vencedor ou empate vale 1 ponto.','No Ranking você acompanha a classificação geral.','No Admin, Kelly vê todos os palpites, lança resultados e limpa ranking.'].map((t,i)=>`<div class="card row"><div style="font-size:40px">${['📝','⚽','✏️','🎯','📊','🔐'][i]}</div><div><h2>${i+1}</h2><p>${t}</p></div></div>`).join('')}<button class="save" onclick="go('games')">⚽ Começar a palpitar</button>`}
function bindPage(){ $$('[data-act]').forEach(btn=>btn.onclick=()=>changeScore(btn.dataset.game,btn.dataset.side,btn.dataset.act)); $$('[data-save]').forEach(btn=>btn.onclick=()=>saveBet(btn.dataset.save)); const pin=$('#pinBtn'); if(pin) pin.onclick=()=>{if($('#pin').value===ADMIN_PIN){state.admin=true;store.set('admin',true);render();showToast('Admin liberado')}else showToast('PIN incorreto')}; const sr=$('#saveResult'); if(sr) sr.onclick=saveResult; const cr=$('#clearRankBtn'); if(cr) cr.onclick=clearRanking; const seed=$('#seedBtn'); if(seed) seed.onclick=()=>{state.games=BR_GAMES;store.set('games',state.games);render();showToast('Jogos restaurados')}; const ex=$('#exportBtn'); if(ex) ex.onclick=exportBets; const imp=$('#importGames'); if(imp) imp.onclick=importGames; const auto=$('#autoBtn'); if(auto) auto.onclick=simulateAuto; const pf=$('#phaseFilter'),sf=$('#statusFilter'); if(pf&&sf){[pf,sf].forEach(x=>x.onchange=filterGames)}}
function changeScore(id,side,act){const el=$(`#${side==='home'?'h':'a'}-${id}`); let n=parseInt(el.textContent||0); n=act==='plus'?n+1:Math.max(0,n-1); el.textContent=n}
function saveBet(id){const g=state.games.find(x=>x.id===id); if(new Date(g.date)<=new Date()) return showToast('Jogo já começou'); const home=parseInt($(`#h-${id}`).textContent), away=parseInt($(`#a-${id}`).textContent); state.bets=state.bets.filter(b=>!(b.gameId===id&&b.phone===state.user.phone)); state.bets.push({gameId:id,phone:state.user.phone,name:state.user.name,home,away,createdAt:new Date().toISOString()}); store.set('bets',state.bets); showToast('Palpite salvo'); render()}
function getBet(id){return state.bets.find(b=>b.gameId===id&&b.phone===state.user?.phone)}
function saveResult(){const id=$('#resGame').value; state.games=state.games.map(g=>g.id===id?{...g,status:'finished',homeScore:+$('#resH').value,awayScore:+$('#resA').value}:g); store.set('games',state.games); render();showToast('Resultado salvo')}
function clearRanking(){if(confirm('Limpar todos os palpites e ranking?')){state.bets=[];store.set('bets',[]);render();showToast('Ranking limpo')}}
function exportBets(){const data='data:text/json;charset=utf-8,'+encodeURIComponent(JSON.stringify(state.bets,null,2)); const a=document.createElement('a');a.href=data;a.download='palpites-bolao.json';a.click()}
function importGames(){try{const arr=JSON.parse($('#jsonGames').value); if(!Array.isArray(arr))throw 0; state.games=arr;store.set('games',arr);render();showToast('Jogos importados')}catch{showToast('JSON inválido')}}
function simulateAuto(){const g=state.games.find(x=>x.status!=='finished'); if(!g)return showToast('Todos encerrados'); g.status='finished';g.homeScore=Math.floor(Math.random()*4);g.awayScore=Math.floor(Math.random()*3);store.set('games',state.games);render();showToast('Atualização automática simulada')}
function scoreBet(b){const g=state.games.find(x=>x.id===b.gameId); if(!g||g.status!=='finished')return null; if(b.home===g.homeScore&&b.away===g.awayScore)return 3; const br=(x,y)=>x>y?'H':x<y?'A':'D'; return br(b.home,b.away)===br(g.homeScore,g.awayScore)?1:0}
function getRanking(){const map={}; state.bets.forEach(b=>{map[b.phone]??={name:b.name,phone:b.phone,pts:0,bets:0}; const s=scoreBet(b); if(s!==null){map[b.phone].pts+=s;map[b.phone].bets++}}); return Object.values(map).sort((a,b)=>b.pts-a.pts||a.name.localeCompare(b.name))}
function rankRows(r){return r.length?r.map((x,i)=>`<div class="rank-row"><b>${i+1}º</b><span><b>${x.name}</b><br><small>${x.phone}</small></span><b>${x.pts} pts</b></div>`).join(''):'<p>Nenhum apostador ainda.</p>'}
function allBetsTable(){return state.bets.length?state.bets.map(b=>{const g=state.games.find(x=>x.id===b.gameId);return `<div class="rank-row"><span>${b.name}<br><small>${b.phone}</small></span><span>${g?.home} x ${g?.away}</span><b>${b.home} x ${b.away}</b></div>`}).join(''):'<p>Nenhum palpite ainda.</p>'}
function filterGames(){const ph=$('#phaseFilter').value, st=$('#statusFilter').value; const list=state.games.filter(g=>(!ph||g.phase===ph)&&(!st||g.status===st)); $('#gamesList').innerHTML=list.map(gameCard).join(''); bindPage()}
function pos(){const r=getRanking(); const i=r.findIndex(x=>x.phone===state.user?.phone); return i<0?'-':`${i+1}º / ${r.length}`}
function fmt(d){return new Date(d).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}
function statusText(g){if(g.status==='finished')return 'Encerrado'; if(g.status==='live')return 'AO VIVO'; const diff=new Date(g.date)-new Date(); if(diff<0)return 'Em breve'; const h=Math.floor(diff/36e5),m=Math.floor(diff%36e5/6e4); return h>24?`${Math.floor(h/24)}d ${h%24}h`:`${h}h ${m}m`}
init();
