const ADMIN_PIN = '2026';
const LS = { user:'bolao_user', games:'bolao_games', bets:'bolao_bets', admin:'bolao_admin' };
const seedGames = [
 {id:'bra-mar-2026',home:'Brasil',away:'Marrocos',date:'13/06/2026 19:00',status:'Encerrado',homeScore:1,awayScore:1},
 {id:'bra-hai-2026',home:'Brasil',away:'Haiti',date:'19/06/2026 21:30',status:'Agendado',homeScore:null,awayScore:null},
 {id:'sco-bra-2026',home:'Escócia',away:'Brasil',date:'24/06/2026 19:00',status:'Agendado',homeScore:null,awayScore:null}
];
let state={user:null,games:load(LS.games,seedGames),bets:load(LS.bets,[]),isAdmin:localStorage.getItem(LS.admin)==='1'};
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function load(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}} function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
function normalizePhone(v){return v.replace(/\D/g,'').slice(0,13)}
function show(id){$$('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active')}
function tab(id){$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));$$('.panel').forEach(p=>p.classList.toggle('active',p.id===id)); if(id==='admin') renderAdmin()}
function ptsFor(b,g){if(g.homeScore==null||g.awayScore==null)return 0; const ex=b.homeGoals==g.homeScore&&b.awayGoals==g.awayScore; const res=Math.sign(b.homeGoals-b.awayGoals)===Math.sign(g.homeScore-g.awayScore); return ex?3:(res?1:0)}
function render(){state.user=load(LS.user,null); if(!state.user){show('#loginScreen');return} show('#homeScreen'); $$('.admin-only').forEach(e=>e.classList.toggle('hidden',!state.isAdmin)); renderGames();renderRanking();renderMyBets();}
function renderGames(){const box=$('#gamesList');box.innerHTML='';state.games.forEach(g=>{const t=$('#gameTpl').content.cloneNode(true);t.querySelector('.status').textContent=g.status;t.querySelector('.date').textContent=g.date;t.querySelector('.home').textContent=g.home;t.querySelector('.away').textContent=g.away;t.querySelector('.score').textContent=g.homeScore==null?'x':`${g.homeScore} x ${g.awayScore}`;const bet=state.bets.find(b=>b.gameId===g.id&&b.phone===state.user.phone);if(bet){t.querySelector('.homeGoals').value=bet.homeGoals;t.querySelector('.awayGoals').value=bet.awayGoals;t.querySelector('.saved').textContent=`Seu palpite: ${bet.homeGoals} x ${bet.awayGoals}`;}t.querySelector('form').addEventListener('submit',e=>{e.preventDefault();const hg=Number(e.target.querySelector('.homeGoals').value), ag=Number(e.target.querySelector('.awayGoals').value);if(Number.isNaN(hg)||Number.isNaN(ag))return alert('Digite o placar.');state.bets=state.bets.filter(b=>!(b.gameId===g.id&&b.phone===state.user.phone));state.bets.push({gameId:g.id,name:state.user.name,phone:state.user.phone,homeGoals:hg,awayGoals:ag,createdAt:new Date().toLocaleString('pt-BR')});save(LS.bets,state.bets);render();alert('Palpite salvo!')});box.appendChild(t)})}
function renderRanking(){const map={};state.bets.forEach(b=>{const g=state.games.find(x=>x.id===b.gameId);map[b.phone]??={name:b.name,phone:b.phone,points:0,exact:0,total:0};const p=ptsFor(b,g||{});map[b.phone].points+=p;map[b.phone].exact+=p===3?1:0;map[b.phone].total++});const arr=Object.values(map).sort((a,b)=>b.points-a.points||b.exact-a.exact);$('#rankingList').innerHTML=arr.length?arr.map((r,i)=>`<div class="rank-item"><div class="rank-pos">${i+1}</div><div><b>${r.name}</b><div class="muted">${r.total} palpites • ${r.exact} exatos</div></div><strong>${r.points} pts</strong></div>`).join(''):'<div class="glass admin-box muted">Ainda não há ranking.</div>'}
function renderMyBets(){const my=state.bets.filter(b=>b.phone===state.user.phone);$('#myBetsList').innerHTML=my.length?my.map(b=>{const g=state.games.find(x=>x.id===b.gameId)||{};return `<div class="game-card glass"><b>${g.home} x ${g.away}</b><p class="muted">${g.date}</p><h3>${b.homeGoals} x ${b.awayGoals}</h3><p class="muted">${b.createdAt}</p></div>`}).join(''):'<div class="glass admin-box muted">Você ainda não enviou palpites.</div>'}
function renderAdmin(){const gate=$('#adminGate'), panel=$('#adminPanel');gate.classList.toggle('hidden',state.isAdmin);panel.classList.toggle('hidden',!state.isAdmin);if(!state.isAdmin)return;panel.innerHTML=`<div class="admin-box glass"><h3>Ferramentas Admin</h3><div class="admin-actions"><button id="clearRank" class="btn danger">Limpar ranking/palpites</button><button id="restoreGames" class="btn">Restaurar jogos Brasil</button></div></div><div class="admin-box glass"><h3>Lançar resultado</h3>${state.games.map(g=>`<div class="admin-actions" style="margin:10px 0"><span>${g.home} x ${g.away}</span><input id="rh_${g.id}" placeholder="${g.home}"><input id="ra_${g.id}" placeholder="${g.away}"><button class="btn small" data-result="${g.id}">Salvar</button></div>`).join('')}</div><div class="admin-box glass"><h3>Todos os palpites</h3><table><thead><tr><th>Nome</th><th>WhatsApp</th><th>Jogo</th><th>Palpite</th></tr></thead><tbody>${state.bets.map(b=>{const g=state.games.find(x=>x.id===b.gameId)||{};return `<tr><td>${b.name}</td><td>${b.phone}</td><td>${g.home} x ${g.away}</td><td>${b.homeGoals} x ${b.awayGoals}</td></tr>`}).join('')||'<tr><td colspan="4">Sem palpites.</td></tr>'}</tbody></table></div><div class="admin-box glass"><h3>Editar jogos via JSON</h3><textarea id="gamesJson" rows="8">${JSON.stringify(state.games,null,2)}</textarea><button id="saveJson" class="btn primary">Salvar JSON</button></div>`;$('#clearRank').onclick=()=>{if(confirm('Limpar todos os palpites e ranking?')){state.bets=[];save(LS.bets,[]);render()}};$('#restoreGames').onclick=()=>{state.games=seedGames;save(LS.games,state.games);render()};$$('[data-result]').forEach(btn=>btn.onclick=()=>{const id=btn.dataset.result;const h=Number($('#rh_'+id).value),a=Number($('#ra_'+id).value);if(Number.isNaN(h)||Number.isNaN(a))return alert('Digite os dois placares.');state.games=state.games.map(g=>g.id===id?{...g,homeScore:h,awayScore:a,status:'Encerrado'}:g);save(LS.games,state.games);render()});$('#saveJson').onclick=()=>{try{state.games=JSON.parse($('#gamesJson').value);save(LS.games,state.games);render()}catch(e){alert('JSON inválido')}}}
$('#loginForm').onsubmit=e=>{e.preventDefault();const user={name:$('#nameInput').value.trim(),phone:normalizePhone($('#phoneInput').value)}; if(user.phone.length<10)return alert('Digite um WhatsApp válido.');save(LS.user,user);render()};$('#logoutBtn').onclick=()=>{localStorage.removeItem(LS.user);render()};$('#adminShortcut').onclick=()=>{save(LS.user,{name:'Admin',phone:'admin'});state.isAdmin=false;tab('admin');render();setTimeout(()=>tab('admin'),50)};$$('.tab').forEach(b=>b.onclick=()=>tab(b.dataset.tab));$('#adminLogin').onclick=()=>{if($('#adminPin').value===ADMIN_PIN){state.isAdmin=true;localStorage.setItem(LS.admin,'1');render();tab('admin')}else alert('PIN incorreto')};if('serviceWorker'in navigator) navigator.serviceWorker.register('sw.js').catch(()=>{});render();
