const TEAMS = [
 ['México','MEX','🇲🇽'],['África do Sul','RSA','🇿🇦'],['Coreia do Sul','KOR','🇰🇷'],['República Tcheca','CZE','🇨🇿'],['Costa do Marfim','CIV','🇨🇮'],['Equador','ECU','🇪🇨'],['Suécia','SWE','🇸🇪'],['Tunísia','TUN','🇹🇳'],['Espanha','ESP','🇪🇸'],['Cabo Verde','CPV','🇨🇻'],['Bélgica','BEL','🇧🇪'],['Egito','EGY','🇪🇬'],['Iraque','IRQ','🇮🇶'],['Noruega','NOR','🇳🇴'],['Brasil','BRA','🇧🇷'],['Alemanha','GER','🇩🇪'],['Argentina','ARG','🇦🇷'],['França','FRA','🇫🇷'],['Portugal','POR','🇵🇹'],['Japão','JPN','🇯🇵'],['Inglaterra','ENG','🏴'],['Uruguai','URU','🇺🇾']
];
const GROUPS='ABCDEFGH'.split('');
const stadiums=['Estádio Azteca, Cidade do México','Lincoln Financial Field, Filadélfia','Mercedes-Benz Stadium, Atlanta','Lumen Field, Seattle','Gillette Stadium, Boston','MetLife Stadium, Nova Jersey','SoFi Stadium, Los Angeles','AT&T Stadium, Dallas'];
let state={user:null,page:'home',drawer:false,games:[],bets:{},users:[],toast:''};
const $=s=>document.querySelector(s), save=()=>localStorage.setItem('bolao2026',JSON.stringify({user:state.user,bets:state.bets,users:state.users,games:state.games}));
function init(){const s=JSON.parse(localStorage.getItem('bolao2026')||'{}');state.user=s.user||null;state.bets=s.bets||{};state.users=s.users||seedUsers();state.games=s.games?.length?s.games:seedGames();if(state.user&&!state.users.find(u=>u.id===state.user.id))state.users.push({...state.user,points:0});render();setInterval(liveUpdate,60000);liveUpdate();if('serviceWorker'in navigator) navigator.serviceWorker.register('sw.js').catch(()=>{});}
function seedUsers(){return[{id:'u1',name:'88996030235',initial:'8',color:'var(--purple)',points:1},{id:'u2',name:'Cleide',initial:'C',color:'var(--orange)',points:1},{id:'u3',name:'49646397204',initial:'4',color:'var(--cyan)',points:0},{id:'u4',name:'Vagner',initial:'V',color:'#2f7cf2',points:0},{id:'u5',name:'VenicyanaSales',initial:'V',color:'#2f7cf2',points:0}]}
function seedGames(){let out=[];let start=new Date('2026-06-14T20:00:00');for(let i=0;i<104;i++){let a=TEAMS[(i*2)%TEAMS.length],b=TEAMS[(i*2+1)%TEAMS.length],d=new Date(start.getTime()+i*3*3600000);let closed=i<2;out.push({id:'g'+i,group:GROUPS[i%8],phase:i<72?'Grupo '+GROUPS[i%8]:(i<88?'16 Avos de Final':i<96?'Oitavas de Final':i<100?'Quartas de Final':i<102?'Semifinal':'Final'),date:d.toISOString(),home:a,away:b,stadium:stadiums[i%stadiums.length],status:closed?'Encerrado':'Aberto',score:closed?[(i%3)+1,i%2]:null});}return out;}
function login(e){e.preventDefault();let f=new FormData(e.target);let name=f.get('name').trim(), user=f.get('user').trim();if(!name||!user)return toast('Preencha usuário e nome.');state.user={id:'me-'+user.toLowerCase(),name:user,full:name,initial:user[0].toUpperCase(),color:'var(--orange)',points:0};state.users=state.users.filter(u=>u.id!==state.user.id);state.users.push({...state.user,points:0});save();render();}
function logout(){state.user=null;save();render();}
function toast(t){state.toast=t;render();setTimeout(()=>{state.toast='';render()},2200)}
function nav(p){state.page=p;state.drawer=false;render();scrollTo(0,0)}
async function liveUpdate(){try{let r=await fetch('/api/live-scores',{cache:'no-store'});if(r.ok){let data=await r.json();if(data.games){data.games.forEach(x=>{let g=state.games.find(g=>g.id===x.id);if(g)Object.assign(g,x)});scoreAll();save();render();}}}catch(e){} }
function scoreAll(){state.users.forEach(u=>u.points=0);Object.entries(state.bets).forEach(([uid,bets])=>{Object.entries(bets).forEach(([gid,b])=>{let g=state.games.find(x=>x.id===gid);if(!g||!g.score)return;let pts=0;if(b.h===g.score[0]&&b.a===g.score[1])pts=3;else if(Math.sign(b.h-b.a)===Math.sign(g.score[0]-g.score[1]))pts=1;let u=state.users.find(x=>x.id===uid);if(u)u.points+=pts;});});if(state.user){let me=state.users.find(u=>u.id===state.user.id);state.user.points=me?.points||0;}}
function fmt(d){let x=new Date(d);return x.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'})+' '+x.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}
function canBet(g){return !g.score && new Date(g.date)>new Date()}
function bet(gid,h,a){state.bets[state.user.id]??={};state.bets[state.user.id][gid]={h:Math.max(0,h),a:Math.max(0,a)};save();render();}
function card(g){let b=state.bets[state.user.id]?.[g.id]||{h:0,a:0};let lock=!canBet(g);return `<div class="card"><div class="match-head"><span class="pill">${g.phase}</span><span>${fmt(g.date)} <b class="pill ${g.status==='Encerrado'?'live':'soon'}">${g.status}</b></span></div><div class="teams"><div><div class="flag">${g.home[2]}</div><div class="team-name">${g.home[0]}</div><div class="abbr">${g.home[1]}</div></div><div class="vs">${g.score?`<span class=score>${g.score[0]} - ${g.score[1]}</span>`:'VS'}</div><div><div class="flag">${g.away[2]}</div><div class="team-name">${g.away[0]}</div><div class="abbr">${g.away[1]}</div></div></div><div class="divider"></div>${g.score?`<div class="small">${state.bets[state.user.id]?.[g.id]?`Seu palpite: ${state.bets[state.user.id][g.id].h} x ${state.bets[state.user.id][g.id].a}`:'Sem palpite neste jogo'}</div>`:`<div class="bet-title">🎯 FAZER PALPITE</div><div class="bet-row"><div><div class="small">${g.home[0]}</div><div class="counter"><button ${lock?'disabled':''} onclick="bet('${g.id}',${b.h-1},${b.a})">−</button><div class="num">${b.h}</div><button ${lock?'disabled':''} onclick="bet('${g.id}',${b.h+1},${b.a})">+</button></div></div><div class="emp">✖<br>empate</div><div><div class="small">${g.away[0]}</div><div class="counter"><button ${lock?'disabled':''} onclick="bet('${g.id}',${b.h},${b.a-1})">−</button><div class="num">${b.a}</div><button ${lock?'disabled':''} onclick="bet('${g.id}',${b.h},${b.a+1})">+</button></div></div></div><button class="save" onclick="toast('Palpite salvo com sucesso!')">Salvar palpite</button>`}<div class="loc">📍 ${g.stadium}</div></div>`}
function topbar(){return `<div class="top"><div class="logo">🐆</div><div class="icons"><span class="ico">☀️</span><span class="ico">🔔</span><button class="avatar" onclick="state.drawer=!state.drawer;render()">${state.user.initial}</button><button class="hamb" onclick="state.drawer=!state.drawer;render()">${state.drawer?'×':'≡'}</button></div></div>`}
function drawer(){let items=[['home','🏠','Início'],['games','⚽','Jogos'],['bracket','🏆','Chaveamento'],['ranking','📊','Ranking'],['stats','📈','Stats'],['tutorial','📖','Tutorial']];return `<div class="drawer ${state.drawer?'open':''}"><div class="drawer-user"><div class="avatar">${state.user.initial}</div><div><h2>${state.user.name}</h2><b style="color:var(--gold)">🏆 ${state.user.points||0} pontos</b></div></div>${items.map(i=>`<div class="menu-item ${state.page===i[0]?'active':''}" onclick="nav('${i[0]}')"><span>${i[1]}</span><b>${i[2]}</b></div>`).join('')}<div class="menu-item" onclick="logout()">🚪 <b>Sair da conta</b></div></div>`}
function bottom(){let items=[['home','🏠','Início'],['games','⚽','Jogos'],['ranking','📊','Ranking'],['stats','📈','Stats']];return `<div class="bottom-nav">${items.map(i=>`<button class="${state.page===i[0]?'active':''}" onclick="nav('${i[0]}')"><span>${i[1]}</span>${i[2]}</button>`).join('')}</div>`}
function home(){return `<div class="hero"><div class="big-logo">🐆</div><h1>Bolão Copa 2026</h1><p>Copa do Mundo 2026 · 11/jun — 19/jul ·<br>EUA, Canadá e México</p><div class="stats3"><div><b>48</b><span>Seleções</span></div><div><b>104</b><span>Jogos</span></div><div><b>16</b><span>Sedes</span></div></div></div><h2 class="section-title">Próximos Jogos <span class="link" onclick="nav('games')">Ver todos</span></h2>${state.games.filter(g=>!g.score).slice(0,3).map(card).join('')}<h2 class="section-title">Top Apostadores <span class="link" onclick="nav('ranking')">Ver todos</span></h2>${rankList().slice(0,5).map((u,i)=>`<div class="rank-row"><b>${i<3?['🥇','🥈','🥉'][i]:i+1+'º'}</b><div class="bubble" style="background:${u.color};width:58px;height:58px;display:inline-grid;margin-right:16px">${u.initial}</div>${u.name}</div><b>${u.points}</b></div>`).join('')}`}
function games(){let groups=[...new Set(state.games.map(g=>g.group))];return `<h1 class="section-title">⚽ Todos os Jogos <span class="pill">104 jogos</span></h1><div class="card filters"><label>Fase<select id="phase" onchange="render()"><option>Todas as fases</option><option>Grupo</option><option>16 Avos de Final</option></select></label><label>Grupo<select id="grp" onchange="render()"><option>Todos os grupos</option>${groups.map(g=>`<option>${g}</option>`).join('')}</select></label></div>${state.games.map(card).join('')}`}
function rankList(){return [...state.users].sort((a,b)=>b.points-a.points)}
function ranking(){let r=rankList();return `<h1 class="section-title">📊 Ranking do Bolão</h1><div class="card"><div class="small" style="text-align:left;letter-spacing:.14em">SISTEMA DE PONTOS</div><div class="grid4"><div class="card statbox"><b style="color:var(--gold)">3</b><span>Placar exato</span></div><div class="card statbox"><b>1</b><span>Vencedor/Empate</span></div><div class="card statbox"><b style="color:#777">0</b><span>Errou</span></div></div></div><div class="rank-podium">${[r[1],r[0],r[2]].map((u,i)=>u?`<div class="pod ${i===1?'first':''}"><div class="bubble" style="background:${u.color}">${u.initial}</div><h2>${u.name}</h2><p>${u.points} pts</p><div style="font-size:32px">${i===1?'🥇':i===0?'🥈':'🥉'}</div></div>`:'').join('')}</div><div class="card rank-list"><div class="rank-row"><b>#</b><b>JOGADOR</b><b>PONTOS</b></div>${r.map((u,i)=>`<div class="rank-row"><b>${i+1}</b><span>${u.name}</span><b>${u.points}</b></div>`).join('')}</div>`}
function stats(){let bets=state.bets[state.user.id]||{}, total=Object.keys(bets).length, pos=rankList().findIndex(u=>u.id===state.user.id)+1;return `<h1 class="section-title"><span class="avatar">${state.user.initial}</span> 📈 Minhas Estatísticas</h1><p class="small" style="text-align:left">${state.user.name}</p><div class="grid4"><div class="card statbox">🏆<b style="color:var(--gold)">${state.user.points||0}</b><span>Pontos totais</span></div><div class="card statbox">📊<b>${pos}º / ${state.users.length}</b><span>Posição</span></div><div class="card statbox">🎯<b>0%</b><span>Aproveitamento</span></div><div class="card statbox">📝<b style="color:white">${total}</b><span>Palpites</span></div></div><div class="card"><h2>Distribuição dos palpites</h2>${['Placar exato (+3)','Acertou vencedor (+1)','Errou (0)','Aguardando'].map(x=>`<p>${x}<b style="float:right">0</b></p><div class="bar"><div style="width:0%"></div></div>`).join('')}<p class="small" style="text-align:left">As estatísticas atualizam automaticamente quando cada jogo encerra.</p></div>`}
function bracket(){return `<h1 class="section-title">🏆 Chaveamento</h1><h2>| 16 AVOS DE FINAL <span class="small">(16 jogos)</span></h2><div class="ko-grid">${Array.from({length:16},(_,i)=>`<div class="ko-card"><div class="time">${fmt(new Date('2026-06-28T16:00:00').getTime()+i*5400000)}</div><div class="line">◼ A definir</div><div class="line">◼ A definir</div></div>`).join('')}</div>`}
function tutorial(){return `<h1 class="section-title">📖 Como funciona o Bolão</h1><p class="small" style="text-align:left">Guia rápido — funciona no celular e no computador</p><div class="tutorial">${[['📝','Crie sua conta','Preencha usuário, nome completo, CPF, data de nascimento, telefone e senha. Esses dados são usados para confirmar o ganhador do prêmio.'],['⚽','Faça seus palpites','Vá em Jogos. Cada jogo abre para palpite 3 dias antes. Toque nos botões + e − e depois em Salvar palpite.'],['✏️','Edite quando quiser','Enquanto o jogo não começa, seu palpite fica salvo e pode ser alterado.'],['🎯','Como pontua','Placar exato = 3 pontos. Acertou só o vencedor ou empate = 1 ponto. Errou = 0.'],['📊','Acompanhe o ranking','Em Ranking você vê a classificação geral. Em Stats vê suas estatísticas.'],['🔴','Placar ao vivo','Os jogos mostram placar ao vivo e o ranking atualiza sozinho quando o jogo termina.']].map((s,i)=>`<div class="card step"><div style="font-size:46px">${s[0]}</div><div><span class="num">${i+1}</span><h2>${s[1]}</h2><p class="small" style="text-align:left;font-size:22px;line-height:1.5">${s[2]}</p></div></div>`).join('')}</div><div class="card"><h2>📲 Instalar como aplicativo</h2><div class="card"><h3 style="color:#ff777c">📱 No celular</h3><p>Android: menu do Chrome → <b>Instalar app</b>.</p><p>iPhone: Safari → Compartilhar → <b>Adicionar à Tela de Início</b>.</p></div><button class="save install" onclick="nav('games')">⚽ Começar a palpitar</button></div>`}
function render(){if(!state.user){document.body.innerHTML=`<div class="login-wrap"><form class="login card" onsubmit="login(event)"><div class="logo">🐆</div><h1>Bolão Copa 2026</h1><p class="small">Entre ou crie sua conta para palpitar</p><input name="user" placeholder="Usuário" required><br><br><input name="name" placeholder="Nome completo" required><br><br><input name="cpf" placeholder="CPF"><br><br><input name="phone" placeholder="Telefone"><br><br><input name="pass" type="password" placeholder="Senha"><button>Entrar / Criar conta</button></form></div>`;return}scoreAll();let pages={home, games, ranking, stats, bracket, tutorial};document.body.innerHTML=topbar()+`<main class="page">${(pages[state.page]||home)()}</main>`+drawer()+bottom()+(state.toast?`<div class="toast">${state.toast}</div>`:'');}
init();
